// Common countries and regions for select dropdowns
export const COUNTRIES = [
    'India',
    'United States',
    'United Kingdom',
    'Canada',
    'Australia',
    'UAE',
    'Singapore',
    'Thailand',
    'Malaysia',
    'Indonesia',
    'Maldives',
    'Sri Lanka',
    'Nepal',
    'Bhutan',
    'Bangladesh',
    'France',
    'Germany',
    'Italy',
    'Spain',
    'Switzerland',
    'Greece',
    'Turkey',
    'Egypt',
    'South Africa',
    'Mauritius',
    'Japan',
    'South Korea',
    'China',
    'Hong Kong',
    'Other',
]

export const REGIONS = [
    'North India',
    'South India',
    'East India',
    'West India',
    'Central India',
    'Northeast India',
    'Middle East',
    'Southeast Asia',
    'South Asia',
    'East Asia',
    'Europe',
    'North America',
    'South America',
    'Africa',
    'Oceania',
    'Other',
]

// Country to Regions mapping
export const COUNTRY_REGIONS = {
    'India': ['North India', 'South India', 'East India', 'West India', 'Central India', 'Northeast India'],
    'UAE': ['Middle East'],
    'Singapore': ['Southeast Asia'],
    'Thailand': ['Southeast Asia'],
    'Malaysia': ['Southeast Asia'],
    'Indonesia': ['Southeast Asia'],
    'Maldives': ['South Asia'],
    'Sri Lanka': ['South Asia'],
    'Nepal': ['South Asia'],
    'Bhutan': ['South Asia'],
    'Bangladesh': ['South Asia'],
    'Japan': ['East Asia'],
    'South Korea': ['East Asia'],
    'China': ['East Asia'],
    'Hong Kong': ['East Asia'],
    'France': ['Europe'],
    'Germany': ['Europe'],
    'Italy': ['Europe'],
    'Spain': ['Europe'],
    'Switzerland': ['Europe'],
    'Greece': ['Europe'],
    'Turkey': ['Europe', 'Middle East'],
    'United States': ['North America'],
    'Canada': ['North America'],
    'Australia': ['Oceania'],
    'Egypt': ['Africa', 'Middle East'],
    'South Africa': ['Africa'],
    'Mauritius': ['Africa'],
    'United Kingdom': ['Europe'],
}

